name:           CatCoreConcepts
version:        0.2

ghc-options: -Wall
synopsis: GIS as a category 

description: |
    experiment to build the core concept data models with categories 
    the focus is on query not update
dependencies:
  - base >= 4.7 && < 5
  - uniformBase
  - extra
  - constrained-categories
  - containers
  - mtl   # for vault
#  for hgeometry
  - hgeometry 
  - linear
  - hgeometry-combinatorial
  - data-clist
  # - aeson-pretty
  - vector 
  # -- not used
  # - array                    >= 0.5
  # - hgeometry
  # # - hgeometry-ipe            >= 0.14
  # - lens
  # - semigroups
  - vector-circular

library:
  source-dirs: .

executables:
  core:
    main: CatCore.hs
    source-dirs: src
    dependencies: 
      - CatCoreConcepts

tests:
  test1:
    main: Testing.hs
    source-dirs: tests
    # main: Lib.Lawvere_test.hs
    dependencies: 
      - CatCoreConcepts
      - HTF
      - uniformBase
      - QuickCheck 
      - test-invariant
      # - numeric-prelude   # for algebra.Lawas

